### ISSUE TITLE
A bit slow

### ISSUE THREAD

**Issue by ghost** [timothybrooks/hdr-plus#4] opened 2018-01-01 11:34 UTC
The algorythm is a bit slow

**Comment by shockjiang** [comment] 2018-05-11 02:16
do you find a way to speed up the code? @ghost

**Comment by KillerInk** [comment] 2018-07-23 12:23
the problem is that each time halide compile the hdrpipe.
once compiled as lib it can get reused and is fast.
here is  [sample](https://github.com/KillerInk/hdr-plus/blob/dng-stack/src/Main.cpp) how to compile it. you have to change some funcs to accept imageparam.

Big thanks @timothybrooks, FreeDcam love it ;D

**Comment by Entropy512** [comment] 2018-10-30 16:35
@KillerInk It looks like you took over maintenance of FreeDcam from the original author?

I'm definitely going to take a look at your HDR+ enhancement work in further detail when I get back from vacation.  Using libraw appeared to be necessary for you to handle DNGs, but it's really beneficial for Sony E-mount users too because dcraw truncates ARW2s from 14 bits down to 12 on load.  :(

I'd love to figure out a way to implement subpixel alignment.  Also - I've found that for mirrorless cameras (probably doesn't apply to bursts on Android devices), there can be enough shift between frames that a 32 pixel block size with +/-8 pixel search works significantly better in many cases.

**Comment by Entropy512** [comment] 2018-11-01 14:13
dcraw scaling down the bit depth is specific to Sony ARW2 loading - it doesn't affect other cameras.

And yeah - this HDR+ algorithm is severely limited by the lack of distortion and vignetting correction, that's pretty important if you have a Sony 24-105G.  I don't think there's a good way to fix this without reworking alignment and merging to occur after demosaicing.

Subpixel alignment or the ability to correct for camera rotation are definitely needed - the HDR+ results I've gotten are extremely poor compared to using Hugin's align_image_stack, at least for the global scene.  HDR+ does better at eliminating ghosting from subject movement, but lack of subpixel alignment 
or rotation correction (not sure which) leads to everything being slightly blurry.  I'll post some comparisons when I get back from vacation.  Lack of CA correction may also be a contributor, but individual frames are far sharper than the merged result.

**Comment by nafnis** [comment] 2018-12-21 04:51
Hi @KillerInk, i have compiled static libs for Android app follow your [repo](https://github.com/KillerInk/hdr-plus/tree/dng-stack), but the state RawToRgb seems to be not work, the rgb output data is null. 
Do you have any solutions?

**Comment by KillerInk** [comment] 2018-12-21 06:37
Hi. I made it only compile and did not spend more time into it. For me it outputs a black and white img. Thats caused by the black whitelvl substraction. Whitelvl is in my case to high and must get calculated depending on the bit depth. Im also not sure if the demosaic part works correct with the hardcoded matrix. Im currently fighting with gradle to get it building with the android plugin. Gradle can be a beast

**Comment by hiepgaf** [comment] 2019-01-23 08:04
Hi @KillerInk, i was make RawToRgb stage to work, but it have a problem.
Without tone_map apply in finish, result:
https://imgur.com/xvCx5x8

With tone_map was applied:
https://imgur.com/xvCx5x8

Do you have any solutions?

**Comment by KillerInk** [comment] 2019-01-23 09:48
@hiepgaf 
Looks like links are the same.
but the image looks a bit purple. so its probably the whitebalance/tint.

what changes have you made?

**Comment by hiepgaf** [comment] 2019-01-23 09:58
@KillerInk 
Please check this [https://imgur.com/a/Is4Y3x7](url)

I was use libraw to read whiteblance, white point and blackpoint instead of use custom matrix.

**Comment by KillerInk** [comment] 2019-01-23 10:06
@hiepgaf  would say that the compression is to high or the gain lvl to low.
that are the only two factors that affecting it.

**Comment by hiepgaf** [comment] 2019-01-23 10:59
@KillerInk I have tried some modify with gain and compression values but nothing change.
When i run on PC with same gain and compression value, the result seem OK. 
https://imgur.com/a/LeCjmAH

Reference image: https://photos.google.com/share/AF1QipPhjjwGoqPszXw6YwZSgqSfyz23d0KT-KuQrKkivhvKIkGeAn6jb8OjSB_dnGQD8g/photo/AF1QipNTlrHapAZR5TLFY2YXrkKsWX9rw4CSd04qYTiy?key=MFZnZUF6NnhlSXotNkxmdzNuX2hoS25vUTRnUzNR

I don't know how different when run on PC and AOT on Android.

**Comment by KillerInk** [comment] 2019-01-23 11:32
@hiepgaf normaly they should produce a simliar output.
i dont know how your pipeline looks like.
i think on pc you have one pipeline rawstack + rawtorgb. and on android you have it splittet.
if thats the case try it on android as one pipe.

**Comment by hiepgaf** [comment] 2019-01-23 11:57
@KillerInk In PC my pipeline is only rawtorgb ;(

**Comment by KillerInk** [comment] 2019-01-23 12:37
@hiepgaf you are building libs from same source set?
feel free to hit [me ](https://t.me/killerInk)on telegram

**Comment by timothybrooks** [comment] 2019-02-12 03:47
Closing the issue as discussion seems to have veered from algorithm speed. Feel free to reopen specifically for runtime improvements.

**Closed by timothybrooks** 2019-02-12 03:47 UTC
